# NumPy stands for numerical python and is the core library for numeric and scientific computing .

It consists of multi-dimensional array object and a collection of routines for processing those arrays.

# Single - Dimensional Array

In [1]:
import numpy as np 

In [2]:
n1 = np.array ([12,23,34,45])
n1

array([12, 23, 34, 45])

# Multi - Dimensional Array 

In [4]:
n2 = np.array([[10,12,23,34,45,64],[34,45,32,56,67,12,56]])
n2

/Users/a1s1cmd/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([10, 12, 23, 34, 45, 64]), list([34, 45, 32, 56, 67, 12, 56])],
      dtype=object)

In [5]:
type(n1)

numpy.ndarray

In [7]:
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [8]:
n4 = np.zeros((6,8))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
type(n4)

numpy.ndarray

In [12]:
n5 = np.full((5,3),12)
n5

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [13]:
n6 = np.arange(12,23)
n6

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [15]:
n7 = np.arange(100,1000,50)
n7

array([100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700,
       750, 800, 850, 900, 950])

In [16]:
type(n7)

numpy.ndarray

In [19]:
n8 = np.random.randint(10,1000,50)
n8

array([685, 374, 100, 380, 627, 257, 882, 914, 294, 447, 451, 207, 116,
       456, 788, 460, 870, 224,  94, 728, 641, 933, 324, 321, 739, 410,
        81, 667, 159, 783, 630, 668, 575,  24, 449, 123, 608, 187, 365,
       997, 961, 964,  82,  70, 250, 800, 385, 160, 636, 478])

In [20]:
n9 = np.array([[1,2,3],[4,5,6]])
n9.shape

(2, 3)

In [ ]:
n4.shape = (4,3)
