# NumPy stands for numerical python and is the core library for numeric and scientific computing .

It consists of multi-dimensional array object and a collection of routines for processing those arrays.

# Single - Dimensional Array

In [2]:
import numpy as np 

In [3]:
n1 = np.array ([12,23,34,45])
n1

array([12, 23, 34, 45])

# Multi - Dimensional Array 

In [4]:
n2 = np.array([[10,12,23,34,45,64],[34,45,32,56,67,12,56]])
n2

/Users/a1s1cmd/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([10, 12, 23, 34, 45, 64]), list([34, 45, 32, 56, 67, 12, 56])],
      dtype=object)

In [5]:
type(n1)

numpy.ndarray

In [6]:
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [7]:
n4 = np.zeros((6,8))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
type(n4)

numpy.ndarray

In [9]:
n5 = np.full((5,3),12)
n5

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [10]:
n6 = np.arange(12,23)
n6

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [11]:
n7 = np.arange(100,1000,50)
n7

array([100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700,
       750, 800, 850, 900, 950])

In [12]:
type(n7)

numpy.ndarray

In [13]:
n8 = np.random.randint(10,1000,50)
n8

array([611, 793, 952, 487, 191, 807, 475, 559, 632, 546, 483, 681, 873,
       536, 779, 949, 506, 421, 645, 426, 446, 900, 592, 200, 804, 564,
       366,  67, 847, 445, 452, 691, 465, 664, 545, 712, 131, 690, 874,
       343, 467, 859, 660, 578, 969, 250, 901, 867, 977, 341])

In [14]:
n9 = np.array([[1,2,3],[4,5,6]])
n9.shape

(2, 3)

In [15]:
n9.shape = (3,2)
n9.shape

(3, 2)

In [16]:
n9

array([[1, 2],
       [3, 4],
       [5, 6]])

# vstack()

In [17]:
n1=np.array([12,23,34])
n2=np.array([45,56,67])

np.vstack((n1,n2))

array([[12, 23, 34],
       [45, 56, 67]])

# hstack()

In [18]:
n1=np.array([12,23,34])
n2=np.array([45,56,67])

np.hstack((n1,n2))

array([12, 23, 34, 45, 56, 67])

# column_stack()

In [20]:
n1=np.array([12,23,34])
n2=np.array([45,56,67])

np.column_stack((n1,n2))

array([[12, 45],
       [23, 56],
       [34, 67]])

In [21]:
n1=np.array([10,20,30,40,50,60,70,80,90,100])
n2=np.array([20,40,60,80,100,120,140])

np.intersect1d(n1,n2)

array([ 20,  40,  60,  80, 100])

In [22]:
n1=np.array([10,20,30,40,50,60,70,80,90,100])
n2=np.array([20,40,60,80,100,120,140])

np.setdiff1d(n1,n2)

array([10, 30, 50, 70, 90])

In [24]:
n1=np.array([10,20,30,40,50,60,70,80,90,100])
n2=np.array([20,40,60,80,100,120,140])

np.setdiff1d(n2,n1)

array([120, 140])

# Addition of NumPy Arrays

In [26]:
n1=np.array([10,20])
n2=np.array([20,40])

np.sum([n1,n2])

90

In [ ]:
np.sum()